-- GENERATED by scripts/generate-seed.ts — READ-ONLY diagnosis, changes nothing.
-- Supabase → SQL Editor → paste → Run. One row per table in schema public:
--   OK        exists with the structure Ayala OS expects
--   FALTA     does not exist yet (setup.sql will create it)
--   DISTINTA  exists but lacks columns Ayala OS needs (setup.sql will stop)
--   AJENA     table not used by Ayala OS (setup.sql never touches it)
with expected(tbl, cols) as (
  values
    ('users', array['id', 'auth_user_id', 'email', 'display_name', 'timezone', 'created_at', 'updated_at']::text[]),
    ('instagram_accounts', array['id', 'user_id', 'ig_user_id', 'username', 'display_name', 'account_type', 'profile_picture_url', 'followers_count', 'media_count', 'access_token_encrypted', 'token_expires_at', 'granted_scopes', 'connection_status', 'last_sync_at', 'last_sync_status', 'last_sync_error', 'sync_locked_until', 'created_at', 'updated_at']::text[]),
    ('sync_runs', array['id', 'account_id', 'kind', 'status', 'started_at', 'finished_at', 'posts_created', 'posts_updated', 'snapshots_written', 'account_days_written', 'errors']::text[]),
    ('posts', array['id', 'account_id', 'ig_media_id', 'media_type', 'media_product_type', 'caption', 'permalink', 'thumbnail_url', 'thumbnail_path', 'published_at', 'duration_sec', 'is_deleted', 'raw', 'first_seen_at', 'created_at', 'updated_at']::text[]),
    ('post_insights', array['id', 'post_id', 'captured_on', 'captured_at', 'views', 'reach', 'likes', 'comments', 'shares', 'saves', 'follows', 'profile_visits', 'total_interactions', 'avg_watch_time_sec', 'extra']::text[]),
    ('account_insights', array['id', 'account_id', 'date', 'followers', 'follows_gained', 'unfollows', 'reach', 'views', 'likes', 'comments', 'shares', 'saves', 'profile_visits', 'extra', 'captured_at']::text[]),
    ('taxonomy_dimensions', array['key', 'label', 'description', 'sort_order']::text[]),
    ('taxonomy_values', array['id', 'dimension', 'slug', 'label', 'parent_id', 'description', 'active', 'created_at', 'updated_at']::text[]),
    ('content_tags', array['id', 'post_id', 'value_id', 'dimension', 'source', 'confidence', 'model', 'rationale', 'created_at', 'updated_at']::text[]),
    ('claude_analyses', array['id', 'account_id', 'kind', 'question', 'answer', 'period_from', 'period_to', 'tool_calls', 'model', 'input_tokens', 'output_tokens', 'created_at']::text[]),
    ('strategy_recommendations', array['id', 'account_id', 'insight_key', 'kind', 'title', 'data', 'interpretation', 'hypothesis', 'recommendation', 'confidence', 'caveats', 'source', 'analysis_id', 'period_from', 'period_to', 'status', 'created_at']::text[]),
    ('experiments', array['id', 'account_id', 'name', 'hypothesis', 'metric', 'baseline', 'baseline_description', 'test', 'start_date', 'end_date', 'status', 'result', 'result_sample_size', 'conclusion', 'recommendation_id', 'created_at', 'updated_at']::text[]),
    ('experiment_results', array['id', 'experiment_id', 'post_id', 'arm', 'metric_value', 'measured_at', 'notes']::text[]),
    ('post_latest_insights', array[]::text[])
),
rel as (
  select e.tbl, e.cols, to_regclass('public.' || e.tbl) is not null as present,
         array(select unnest(e.cols) except
               select c.column_name::text from information_schema.columns c
               where c.table_schema = 'public' and c.table_name = e.tbl) as missing
  from expected e
  union all
  select t.table_name::text, array[]::text[], true, null
  from information_schema.tables t
  where t.table_schema = 'public' and t.table_name::text not in (select tbl from expected)
)
select tbl as tabla,
       case when missing is null then 'AJENA'
            when not present then 'FALTA'
            when cardinality(missing) = 0 then 'OK'
            else 'DISTINTA' end as estado,
       case when present then (xpath('/row/n/text()',
              query_to_xml(format('select count(*) as n from public.%I', tbl), false, true, '')))[1]::text::bigint
       end as filas,
       nullif(array_to_string(missing, ', '), '') as columnas_que_faltan
from rel
order by (missing is null), tbl;
