-- GENERATED by scripts/generate-seed.ts — do not edit by hand.
-- Initial taxonomy. Presence here does not mean a topic works; the data decides.

insert into public.taxonomy_dimensions (key, label, description, sort_order) values
  ('topic', 'Topic', 'Tema principal del contenido', 0),
  ('subtopic', 'Subtopic', 'Ángulo concreto dentro del tema', 1),
  ('hook', 'Hook', 'Mecanismo de apertura (primeros 1–3 s)', 2),
  ('cta', 'CTA', 'Llamada a la acción', 3),
  ('format', 'Format', 'Formato de producción', 4),
  ('visual_style', 'Visual style', 'Contexto visual', 5),
  ('audio', 'Audio', 'Tipo de audio', 6)
on conflict (key) do nothing;

insert into public.taxonomy_values (dimension, slug, label, description) values
  ('topic', 'falta-de-tiempo', 'Falta de tiempo', null),
  ('topic', 'cansancio', 'Cansancio', null),
  ('topic', 'consistencia', 'Consistencia', null),
  ('topic', 'fuerza', 'Fuerza', null),
  ('topic', 'cardio', 'Cardio', null),
  ('topic', 'nutricion', 'Nutrición', null),
  ('topic', 'perdida-de-grasa', 'Pérdida de grasa', null),
  ('topic', 'habitos', 'Hábitos', null),
  ('topic', 'sueno', 'Sueño', null),
  ('topic', 'estres', 'Estrés', null),
  ('topic', 'entrenamiento-eficiente', 'Entrenamiento eficiente', null),
  ('subtopic', 'cansancio-post-trabajo', 'Cansancio después del trabajo', null),
  ('subtopic', 'entrenos-cortos', 'Entrenos de 30 min o menos', null),
  ('subtopic', 'viajes-trabajo', 'Entrenar viajando por trabajo', null),
  ('subtopic', 'volver-a-empezar', 'Volver a empezar', null),
  ('subtopic', 'comer-fuera', 'Comer fuera / menú del día', null),
  ('subtopic', 'proteina-facil', 'Proteína fácil', null),
  ('subtopic', 'fuerza-basica', 'Básicos de fuerza', null),
  ('hook', 'problem-solution', 'Problem / solution', null),
  ('hook', 'pregunta', 'Pregunta directa', null),
  ('hook', 'mito', 'Mito / creencia falsa', null),
  ('hook', 'error-comun', 'Error común', null),
  ('hook', 'historia-personal', 'Historia personal / cliente', null),
  ('hook', 'lista', 'Lista (X cosas…)', null),
  ('hook', 'contraintuitivo', 'Afirmación contraintuitiva', null),
  ('cta', 'comenta-palabra', 'Comenta palabra clave', 'Ej.: "Comenta CARDIO"'),
  ('cta', 'guarda', 'Guárdalo', null),
  ('cta', 'comparte', 'Compártelo', null),
  ('cta', 'sigueme', 'Sígueme', null),
  ('cta', 'dm', 'Escríbeme por DM', null),
  ('cta', 'link-bio', 'Link en bio', null),
  ('cta', 'sin-cta', 'Sin CTA', null),
  ('format', 'talking-head', 'Talking head', null),
  ('format', 'talking-head-broll', 'Talking head + B-roll', null),
  ('format', 'voiceover-broll', 'Voice-over + B-roll', null),
  ('format', 'texto-en-pantalla', 'Texto en pantalla', null),
  ('format', 'tutorial-ejercicio', 'Tutorial de ejercicio', null),
  ('format', 'carrusel-educativo', 'Carrusel educativo', null),
  ('visual_style', 'gym', 'Gimnasio', null),
  ('visual_style', 'casa', 'Casa', null),
  ('visual_style', 'exterior', 'Exterior', null),
  ('visual_style', 'oficina', 'Oficina / trabajo', null),
  ('visual_style', 'diseno-grafico', 'Diseño gráfico', null),
  ('audio', 'voz-original', 'Voz original', null),
  ('audio', 'trending', 'Audio en tendencia', null),
  ('audio', 'musica-libre', 'Música de librería', null),
  ('audio', 'sin-audio', 'Sin audio', null)
on conflict (dimension, slug) do nothing;

-- Subtopic → topic links
update public.taxonomy_values c set parent_id = p.id from public.taxonomy_values p where c.dimension = 'subtopic' and c.slug = 'cansancio-post-trabajo' and p.dimension = 'topic' and p.slug = 'cansancio' and c.parent_id is null;
update public.taxonomy_values c set parent_id = p.id from public.taxonomy_values p where c.dimension = 'subtopic' and c.slug = 'entrenos-cortos' and p.dimension = 'topic' and p.slug = 'falta-de-tiempo' and c.parent_id is null;
update public.taxonomy_values c set parent_id = p.id from public.taxonomy_values p where c.dimension = 'subtopic' and c.slug = 'viajes-trabajo' and p.dimension = 'topic' and p.slug = 'falta-de-tiempo' and c.parent_id is null;
update public.taxonomy_values c set parent_id = p.id from public.taxonomy_values p where c.dimension = 'subtopic' and c.slug = 'volver-a-empezar' and p.dimension = 'topic' and p.slug = 'consistencia' and c.parent_id is null;
update public.taxonomy_values c set parent_id = p.id from public.taxonomy_values p where c.dimension = 'subtopic' and c.slug = 'comer-fuera' and p.dimension = 'topic' and p.slug = 'nutricion' and c.parent_id is null;
update public.taxonomy_values c set parent_id = p.id from public.taxonomy_values p where c.dimension = 'subtopic' and c.slug = 'proteina-facil' and p.dimension = 'topic' and p.slug = 'nutricion' and c.parent_id is null;
update public.taxonomy_values c set parent_id = p.id from public.taxonomy_values p where c.dimension = 'subtopic' and c.slug = 'fuerza-basica' and p.dimension = 'topic' and p.slug = 'fuerza' and c.parent_id is null;
