/**
 * Generates supabase/seed.sql from src/lib/data/taxonomy-seed.ts so the
 * initial taxonomy has a single source. Run: npm run db:seed:generate
 * The seed is idempotent (ON CONFLICT DO NOTHING) and never overwrites edits.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { TAXONOMY_DIMENSIONS, TAXONOMY_SEED } from "../src/lib/data/taxonomy-seed";

const q = (s: string | undefined | null) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`);

const lines = [
  "-- GENERATED by scripts/generate-seed.ts — do not edit by hand.",
  "-- Initial taxonomy. Presence here does not mean a topic works; the data decides.",
  "",
  "insert into public.taxonomy_dimensions (key, label, description, sort_order) values",
  TAXONOMY_DIMENSIONS.map((d, i) => `  (${q(d.key)}, ${q(d.label)}, ${q(d.description)}, ${i})`).join(",\n"),
  "on conflict (key) do nothing;",
  "",
  "insert into public.taxonomy_values (dimension, slug, label, description) values",
  TAXONOMY_SEED.map((v) => `  (${q(v.dimension)}, ${q(v.slug)}, ${q(v.label)}, ${q(v.description)})`).join(",\n"),
  "on conflict (dimension, slug) do nothing;",
  "",
  "-- Subtopic → topic links",
  ...TAXONOMY_SEED.filter((v) => v.parent).map(
    (v) =>
      `update public.taxonomy_values c set parent_id = p.id from public.taxonomy_values p ` +
      `where c.dimension = 'subtopic' and c.slug = ${q(v.slug)} and p.dimension = 'topic' and p.slug = ${q(v.parent)} and c.parent_id is null;`,
  ),
  "",
];

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n"));

// One-paste setup for the Supabase SQL Editor: schema + seed in a single file.
const schema = readFileSync(new URL("../supabase/migrations/20260929000001_initial_schema.sql", import.meta.url), "utf8");
writeFileSync(
  new URL("../supabase/setup.sql", import.meta.url),
  `-- GENERATED by scripts/generate-seed.ts — schema + initial taxonomy in one file.\n-- Supabase → SQL Editor → paste everything → Run (on a new, empty project).\n\n${schema}\n\n${lines.join("\n")}`,
);
console.log(`seed.sql written: ${TAXONOMY_DIMENSIONS.length} dimensions, ${TAXONOMY_SEED.length} values`);
