/**
 * Generates supabase/seed.sql from src/lib/data/taxonomy-seed.ts so the
 * initial taxonomy has a single source, plus supabase/setup.sql (schema + seed,
 * guarded, one transaction) and supabase/check.sql (read-only diagnosis).
 * Run: npm run db:seed:generate
 * The seed is idempotent (ON CONFLICT DO NOTHING) and never overwrites edits.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { TAXONOMY_DIMENSIONS, TAXONOMY_SEED } from "../src/lib/data/taxonomy-seed";
import { expectedTablesValuesSql } from "./expected-schema";

const q = (s: string | undefined | null) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`);

const lines = [
  "-- GENERATED by scripts/generate-seed.ts — do not edit by hand.",
  "-- Initial taxonomy. Presence here does not mean a topic works; the data decides.",
  "",
  "insert into public.taxonomy_dimensions (key, label, description, sort_order) values",
  TAXONOMY_DIMENSIONS.map((d, i) => `  (${q(d.key)}, ${q(d.label)}, ${q(d.description)}, ${i})`).join(",\n"),
  "on conflict (key) do nothing;",
  "",
  "insert into public.taxonomy_values (dimension, slug, label, description) values",
  TAXONOMY_SEED.map((v) => `  (${q(v.dimension)}, ${q(v.slug)}, ${q(v.label)}, ${q(v.description)})`).join(",\n"),
  "on conflict (dimension, slug) do nothing;",
  "",
  "-- Subtopic → topic links",
  ...TAXONOMY_SEED.filter((v) => v.parent).map(
    (v) =>
      `update public.taxonomy_values c set parent_id = p.id from public.taxonomy_values p ` +
      `where c.dimension = 'subtopic' and c.slug = ${q(v.slug)} and p.dimension = 'topic' and p.slug = ${q(v.parent)} and c.parent_id is null;`,
  ),
  "",
];

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n"));

// Guard: if a table with one of our names exists but lacks our columns, it is
// not ours — abort before touching anything.
const guard = `do $guard$
declare
  r record;
  bad text := '';
begin
  for r in
    select e.tbl,
           array(select unnest(e.cols) except
                 select c.column_name::text from information_schema.columns c
                 where c.table_schema = 'public' and c.table_name = e.tbl) as missing
    from (values
${expectedTablesValuesSql()}
    ) as e(tbl, cols)
    where to_regclass('public.' || e.tbl) is not null
  loop
    if cardinality(r.missing) > 0 then
      bad := bad || format(E'\\n  public.%s: faltan columnas %s', r.tbl, array_to_string(r.missing, ', '));
    end if;
  end loop;
  if bad <> '' then
    raise exception 'Ayala OS: hay tablas con el mismo nombre pero otra estructura. No se ha modificado nada.%', bad
      using hint = 'Ejecuta supabase/check.sql y revisa esas tablas antes de decidir.';
  end if;
end $guard$;`;

// One-paste setup for the Supabase SQL Editor: schema + seed in a single file,
// idempotent and all-or-nothing (one transaction).
const schema = readFileSync(new URL("../supabase/migrations/20260929000001_initial_schema.sql", import.meta.url), "utf8");
writeFileSync(
  new URL("../supabase/setup.sql", import.meta.url),
  [
    "-- GENERATED by scripts/generate-seed.ts — schema + initial taxonomy in one file.",
    "-- Supabase → SQL Editor → paste everything → Run.",
    "-- Safe to run more than once: creates only what is missing, never drops or",
    "-- overwrites data, and runs in a single transaction (all or nothing).",
    "",
    "begin;",
    "",
    guard,
    "",
    schema,
    "",
    ...lines,
    "commit;",
    "",
  ].join("\n"),
);

// Read-only diagnosis: one row per table, with status and row count.
writeFileSync(
  new URL("../supabase/check.sql", import.meta.url),
  `-- GENERATED by scripts/generate-seed.ts — READ-ONLY diagnosis, changes nothing.
-- Supabase → SQL Editor → paste → Run. One row per table in schema public:
--   OK        exists with the structure Ayala OS expects
--   FALTA     does not exist yet (setup.sql will create it)
--   DISTINTA  exists but lacks columns Ayala OS needs (setup.sql will stop)
--   AJENA     table not used by Ayala OS (setup.sql never touches it)
with expected(tbl, cols) as (
  values
${expectedTablesValuesSql()},
    ('post_latest_insights', array[]::text[])
),
rel as (
  select e.tbl, e.cols, to_regclass('public.' || e.tbl) is not null as present,
         array(select unnest(e.cols) except
               select c.column_name::text from information_schema.columns c
               where c.table_schema = 'public' and c.table_name = e.tbl) as missing
  from expected e
  union all
  select t.table_name::text, array[]::text[], true, null
  from information_schema.tables t
  where t.table_schema = 'public' and t.table_name::text not in (select tbl from expected)
)
select tbl as tabla,
       case when missing is null then 'AJENA'
            when not present then 'FALTA'
            when cardinality(missing) = 0 then 'OK'
            else 'DISTINTA' end as estado,
       case when present then (xpath('/row/n/text()',
              query_to_xml(format('select count(*) as n from public.%I', tbl), false, true, '')))[1]::text::bigint
       end as filas,
       nullif(array_to_string(missing, ', '), '') as columnas_que_faltan
from rel
order by (missing is null), tbl;
`,
);
console.log(`seed.sql, setup.sql, check.sql written: ${TAXONOMY_DIMENSIONS.length} dimensions, ${TAXONOMY_SEED.length} values`);
